In [54]:
import torch
import torch.nn.functional as F

In [55]:
order = 2
x = torch.Tensor([1,1,0,0,0,1,0,1,1,1,0,0,1])
y = torch.Tensor([1,0,0,0,1,0,1,1,1,0,0,1,1])
powers = torch.Tensor([2**i for i in reversed(range(order))])

In [56]:
print(x)
print(powers)

tensor([1., 1., 0., 0., 0., 1., 0., 1., 1., 1., 0., 0., 1.])
tensor([2., 1.])


In [57]:
idx = F.conv1d(x.view(1,-1),powers.view(1,1,-1)).squeeze()
print(idx)

tensor([3., 2., 0., 0., 1., 2., 1., 3., 3., 2., 0., 1.])


In [58]:
mask = (idx == 1)
print(mask)

tensor([False, False, False, False,  True, False,  True, False, False, False,
        False,  True])


In [59]:
s = y[order-1:][mask]
print(s)

tensor([0., 1., 1.])


In [60]:
s = torch.cat((torch.Tensor([0]),s[:-1]))
s = (s.cumsum(0)+0.5) / (torch.arange(0,len(s)) + 1)

tensor([0.5000, 0.2500, 0.5000])
